# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'XavierDemoiOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for XavierDemoiOS

  pod 'XLPagerTabStrip', '~> 8.1'
  pod 'TesseractOCRSDKiOS', '~> 4.0'
  pod 'EVGPUImage2', '~> 0.2'

end
